tap "homebrew/bundle"
tap "mas-cli/tap"
tap "universal-ctags/universal-ctags"
tap "fluxcd/tap"

brew "mas-cli/tap/mas"

mas "Xcode", id: 497_799_835

brew "aws-cdk"
brew "awscli"
brew "aws-sam-cli"
brew "docker"
brew "git-secrets"
brew "go"
brew "gotags"
brew "helm"
brew "java"
brew "kubernetes-cli"
brew "eksctl"
brew "istioctl"
brew "logcli"
brew "maven"
brew "minikube"
brew "nodejs"
brew "neovim"
brew "python"
brew "qemu"
brew "terraform"
brew "tmux"
brew "universal-ctags"
brew "vim"
brew "watch"
brew "wireguard-tools"

cask "font-jetbrains-mono-nerd-font"
cask "drawio"
cask "google-chrome"
cask "google-drive"
cask "raspberry-pi-imager"
cask "session-manager-plugin"
cask "slack"
cask "ultimaker-cura"
