
require('options')
require('filetypes')
require('keymaps')
require('colorscheme')
require('plugins')
require('lsp')

require('config.tmuxline')
require('config.lualine')
require('config.treesitter')
require('config.nerdtree')
require('config.tagbar')
require('config.vim-go')
require('config.vim-terraform')
