
require('options')
require('filetypes')
require('keymaps')
require('plugins')
require('colorscheme')
require('lsp')

require('config.tmuxline')
require('config.vim-airline')
require('config.nerdtree')
require('config.tagbar')
require('config.vim-go')
require('config.vim-terraform')
require('config.haskell-vim')
